build:
  tags:
    - x86_64-linux
  image: nixos/nix:latest
  script:
    # move one directory up (we're already in the checkout of ghc.nix) 
    - cd ..
    # set p git
    - git config --global url."git://github.com/ghc/packages-".insteadOf     git://github.com/ghc/packages/ &&
    - git config --global url."http://github.com/ghc/packages-".insteadOf    http://github.com/ghc/packages/ &&
    - git config --global url."https://github.com/ghc/packages-".insteadOf   https://github.com/ghc/packages/ &&
    - git config --global url."ssh://git@github.com/ghc/packages-".insteadOf ssh://git@github.com/ghc/packages/ &&
    - git config --global url."git@github.com:ghc/packages-".insteadOf       git@github.com:ghc/packages/
    - git clone --recurse-submodules https://gitlab.haskell.org/ghc/ghc.git

    # set up nix
    - mkdir -p ~/.config/nix
    - echo "extra-experimental-features = nix-command flakes" > ~/.config/nix/nix.conf
    - nix profile install --impure nixpkgs#cachix
    - cachix use ghc-nix

    # check linting
    - nix flake check ghc.nix# -Lv

    # check GHC builds
    - cd ghc/
    # on legacy commands ...
    - nix-shell --pure ../ghc.nix/shell.nix --command "./boot && configure_ghc"
    - nix-shell --pure ../ghc.nix/shell.nix --command "pushd hadrian; cabal new-update; cabal new-build -j all; popd"
    - nix-shell --pure ../ghc.nix/shell.nix --command "echo :q | hadrian/ghci | tail -n2 | grep 'Ok,'"
    - nix-shell --pure ../ghc.nix/shell.nix --command "hadrian/build -j --flavour=quickest"
    - nix-shell --pure ../ghc.nix/shell.nix --command "hadrian/build -j --flavour=quickest test --test-root-dirs=testsuite/tests/programs"

    # ... and flake commands
    - nix develop -Lv --fallback ../ghc.nix# -c bash -c "./boot && configure_ghc"
    - nix develop -Lv --fallback ../ghc.nix# -c bash -c "pushd hadrian; cabal new-update; cabal new-build -j all; popd"
    - nix develop -Lv --fallback ../ghc.nix# -c bash -c "echo :q | hadrian/ghci | tail -n2 | grep 'Ok,'"
    - nix develop -Lv --fallback ../ghc.nix# -c bash -c "hadrian/build -j --flavour=quickest"
    - nix develop -Lv --fallback ../ghc.nix# -c bash -c "hadrian/build -j --flavour=quickest test --test-root-dirs=testsuite/tests/programs"

    # wasm and js backends smoketest
    - nix develop -Lv --fallback ../ghc.nix#wasm-cross -c bash -c "./boot && configure_ghc"
    - nix develop -Lv --fallback ../ghc.nix#wasi-cross -c true
    - nix develop -Lv --fallback ../ghc.nix#js-cross -c bash -c "./boot && configure_ghc"
