build:
  tags:
    - x86_64-linux
  image: nixos/nix:latest
  script:
    # set p git
    - git config --global url."git://github.com/ghc/packages-".insteadOf     git://github.com/ghc/packages/ &&
    - git config --global url."http://github.com/ghc/packages-".insteadOf    http://github.com/ghc/packages/ &&
    - git config --global url."https://github.com/ghc/packages-".insteadOf   https://github.com/ghc/packages/ &&
    - git config --global url."ssh://git@github.com/ghc/packages-".insteadOf ssh://git@github.com/ghc/packages/ &&
    - git config --global url."git@github.com:ghc/packages-".insteadOf       git@github.com:ghc/packages/
    - git clone --recurse-submodules https://gitlab.haskell.org/ghc/ghc.git

    # set up nix
    - mkdir -p ~/.config/nix
    - echo "extra-experimental-features = nix-command flakes" > ~/.config/nix/nix.conf
    - nix profile install --impure nixpkgs#cachix
    - cachix use ghc-nix

    # check linting
    - ls 
    - pwd
    - nix flake check ghc.nix# -Lv
